### ISSUE TITLE
realisticEjaculations didn't works every time

### ISSUE THREAD

**Issue by ciccabanana** [nwishmaster/HnP_mods#2]
The use of the game variables 86 for check the presence of the condom doesn't work correctly every time.
https://github.com/nwishmaster/HnP_mods/blob/131d3b235a4231e522fd7e9102e84865f54bf316/src/MOD_realisticEjaculations.js#L11
I checked the list of variable and switch, and i found that the game switch 86 correctly display if the partner wear the condom.

I tried to changing the lines 9 to 11:
https://github.com/nwishmaster/HnP_mods/blob/131d3b235a4231e522fd7e9102e84865f54bf316/src/MOD_realisticEjaculations.js#L9-L11
In this way:
```
        const V = $gameVariables._data || {};
        const S = $gameSwitches._data || {};
        const IS_IN_VAGINA = V[328] === 1;
        const WITH_CONDOM = S[86];
```
And tested in game wearing and removing condom during the hotel scene and worked fine every time.

**Comment by nwishmaster** [comment]
@ciccabanana hello there! Sorry for taking too long to response. 

Looks good! Do you want me to do a quick hotfix or you want to open a PR by yourself?
